# Generated by Django 5.2.4 on 2025-07-10 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField(verbose_name='출발지 위도')),
                ('origin_lng', models.FloatField(verbose_name='출발지 경도')),
                ('hos_lat', models.FloatField(verbose_name='병원 위도')),
                ('hos_lng', models.FloatField(verbose_name='병원 경도')),
                ('estimated_time', models.IntegerField(verbose_name='예상 소요 시간(분)')),
                ('estimated_cost', models.IntegerField(verbose_name='예상 비용(원)')),
                ('distance', models.FloatField(verbose_name='거리(km)')),
                ('requested_at', models.IntegerField(verbose_name='요청 시간')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
