# Generated by Django 5.0.7 on 2025-07-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('hos_lat', models.FloatField(verbose_name='위도')),
                ('hos_lng', models.FloatField(verbose_name='경도')),
                ('phone', models.CharField(max_length=20)),
                ('is_emergency', models.BooleanField(default=False, verbose_name='응급실 여부')),
                ('nightcare', models.BooleanField(default=False, verbose_name='야간진료여부')),
                ('start_hour', models.TimeField(blank=True, null=True, verbose_name='진료 시작 시간')),
                ('end_hour', models.TimeField(blank=True, null=True, verbose_name='진료 종료 시간')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion', models.CharField(choices=[('매우 혼잡', '매우 혼잡'), ('혼잡', '혼잡'), ('보통', '보통'), ('여유', '여유'), ('매우 여유', '매우 여유')], max_length=10)),
                ('available_beds', models.IntegerField()),
                ('waiting_count', models.IntegerField()),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='hospital.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialties',
            field=models.ManyToManyField(related_name='hospitals', to='hospital.specialty'),
        ),
    ]
