# Generated by Django 5.2.4 on 2025-07-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visithistory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='visithistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
